### ISSUE TITLE
Overuse of Snipe command, Limitations will be helpful

### ISSUE THREAD

**Issue by yashppawar** [alvinbengeorge/alfred-discord-bot#30]
Seems like there are many people just overusing the `'snipe` command, which is not good, as the message were deleted because it was not supposed to be read, so It will be better if only moderators were allowed to `'snipe`.

Regards
@yashppawar 😊

**Comment by alvinbengeorge** [comment]
all right I can do that 😄

**Comment by alvinbengeorge** [comment]
but which permissions do you expect it to send for

**Comment by yashppawar** [comment]
Maybe just the people with the highest role/power,  or people with manage messages perms, not sure if @alfred already has it or not, I could not find it in the code.

**Comment by alvinbengeorge** [comment]
Manage messages is everyone in batcave

**Comment by alvinbengeorge** [comment]
oh wait I turned it off ig, so its fine
could you send a message?

**Comment by alvinbengeorge** [comment]
ok I'll add manage messages also

**Comment by alvinbengeorge** [comment]
I think i finished this
