### ISSUE TITLE
No display when the Repo has no License

### ISSUE THREAD

**Issue by yashppawar** [alvinbengeorge/alfred-discord-bot#39]
When the github repo has no license it does not give any reply
 steps to duplicate
`'ghr username/repo_with_no_license`

**Comment by yashppawar** [comment]
admin log:
![image](https://user-images.githubusercontent.com/72196156/136017771-b8c5ef49-6ba3-494a-bc35-9b48a2d2e0b1.png)

**Comment by alvinbengeorge** [comment]
We can go through an if condition to see if its none

**Comment by alvinbengeorge** [comment]
This could be temporary solution
