### ISSUE TITLE
Emoji function deleting all webhooks

### ISSUE THREAD

**Issue by AvanindraC** [alvinbengeorge/alfred-discord-bot#54]
I introduced alfred to a server and it was pretty popular there, but there was a problem
Whenever the emoji commands were used all the webhooks are deleted, and the server uses webhooks quite often
So it causes them some problems
I request you to look into the problem and make so that only the webhooks created by alfred are deleted

**Comment by alvinbengeorge** [comment]
Oh shoot right, I can change it, I basically put it like that, never thought of that
Sorry

**Comment by AvanindraC** [comment]
It's fine
Thanks for responding so fasy

**Comment by alvinbengeorge** [comment]
I think this is done, I fixed it now, thanks for informing
